veresion: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
        name: "lint files"
        command: yarn lint

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
