veresion: 2
jobs:
  build:
    working_directory: ~/ssr-auth/client
    docker:
      - image: circleci/node:latest

    steps:
      - checkout:
          path: ~/ssr-auth

      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          - dependency-cache-

      - run:
          name: "Install dependencies"
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: '.'
          paths:
            - node_modules
            - yarn.lock

  test:
    working_directory: ~/ssr-auth/client
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
          path: ~/ssr-auth
      
      - attach_workspace:
          at: '.'

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: "Lint files"
          command: yarn lint
      - run:
          name: "React test suite"
          command: yarn test:coverage

workflows:
  version: 2
  client_predeploy:
    jobs:
      - build
      - test:
          requires:
            - build